export const ADD_PLAYING_VIDEO = 'ADD_PLAYING_VIDEO';
export const DELETE_PLAYING_VIDEO = 'DELETE_PLAYING_VIDEO';
export const EDIT_PLAYING_VIDEO = 'EDIT_PLAYING_VIDEO';
export const CLEAR_ALL = 'CLEAR_ALL';
